---
title             : "Review: Effects of initial phylogenetic and chronogram hypothesis on evolutionary downstream analyses"
shorttitle        : "Litt review"

author:
  - name          : "Luna L. Sánchez Reyes"
    affiliation   : "1,2"
    corresponding : yes    # Define only one corresponding author
    address       : ""
    email         : "sanchez.reyes.luna@gmail.com"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Data curation
      - Investigation
      - Software
      - Visualization
      - Validation
      - Writing
      - Original Draft Preparation
      - Writing
      - Review & Editing

affiliation:
  - id            : "1"
    institution   : "University of California, Merced, USA"
  - id            : "2"
    institution   : "University of Tennessee, Knoxville, USA"

authornote: |
  School of Natural Sciences, University of California, Merced, 258 Science and Engineering Building 1, Merced, CA 95340, USA.
  Department of Ecology and Evolutionary Biology, University of Tennessee, Knoxville, 446 Hesler Biology Building, Knoxville, TN 37996, USA.
bibliography      : ["paper_references.bib"]
wordcount         : "`r wordcountaddin::word_count()`"
floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no
documentclass     : "apa6"
classoption       : "man"
output            :
  papaja::apa6_pdf:
    includes      :
      in_header: "preamble.tex"
---

```{r setup, include = FALSE}
library("papaja")
r_refs("paper_references.bib")
embed_figure <- TRUE
```

For Discussion
tendency to underestimate ages for topologically deeper nodes, and overestimate ages for nodes closer to the tips. However, node ages obtained with DateLife are generally correlated with those from the dating analysis that used primary calibrations.

@cusimano2012new: Simulating branch lengths following a birth-death species diversification model for
missing taxa to chronograms with non random sampling, lowers type I error (false positive,
incorrectly accepting the null hypothesis of a constant-rate or temporally varying rate
birth-death model) when analyzing changes in diversification rate using the gamma statistic.

@thomas2013pastis hypothesize that results of diversification analyses will be biased towards
the birth-death model used to simulate branch lengths;
and note that "the effects of missing species placement or polytomy resolution are
less clear for other phylogeny-based analyses (e.g. correlates of diversification,
modelling trait evolution, community phylogenetics), and future work should test how the
treatment of missing species influences both parameter estimation and type I and II errors"

@rabosky2015no shows that randomly resolved phylogenies are inappropriate to study trait evolution,
because unresolved lineages are placed on the phylogeny at random relative to the trait values.
At best, LLSR believe these phylogenies could serve as a null hypothesis of randomness in trait evolution.

"birth–death polytomy resolver is a method of accounting for phylogenetic uncertainty that places
missing (unsampled) taxa onto phylogenetic trees, using taxonomic information alone"

Adding branch lengths sampled from a birth-death model in the absence of genetic data
improves insight from phylogeny-based analyses of diversification rates [@chang2020estimating].
@chang2020estimating state that stochastic politomy resolution alleviate low statistical power to
identify shifts in diversification rate with methods that account for sampling fractions.
@chang2020estimating "demonstrate theoretical concerns with the widespread use of analytical
sampling corrections for sparsely sampled phylogenies of higher taxonomic groups. In particular,
corrections based on “sampling fractions” can lead to low statistical power to infer rate variation
when it is present, depending on the likelihood function used for inference. In the extreme, the sampling
fraction correction can lead to spurious patterns of diversification that are driven solely by unbalanced
sampling across the tree in concert with low overall power to infer shifts."

@title2019tip do not test possible estimate biases using phylogenies with randomly
resolved politomies. They analyse complete phylogenies and found that estimating species diversification
rates with model free methods and BAMM is good for speciation rate estimates, but less good for net
diversification rate, and bad for extinction rates.

@sun2020estimating used a 50% species level sampled phylogeny of the family Cucurbitaceae to estimate
speciation rates with two parametric methods (RPANDA and BAMM) and one semi-parametric method (DR) and
tested the effect of using incompletely sampled phylogenies on one hand, and incomplete phylogenies that
have been made near complete, using a stochastic politomy resolver based on taxonomy, on the other hand
(with two different methods: 1) adding missing species at random following a backbone taxonomy, and 2)
adding missing species to a genus level taxonomy based on a taxonomy resolver only). When using incomplete
phylogenies, parametric methods tend to overestimate speciation rate as sampling gets worse (less complete),
while semi-parametric methods tend to underestimate speciation rate as sampling gets worse. When using
taxonomically resolved complete phylogenies, only one parametric method overestimates speciation rate the
more incomplete original sampling was. RPANDA, BAMM tip rates and DR all underestimate speciation rates as
original sampling was more incomplete.
"Adding backbone taxa tends to result in the inference of spurious early bursts of diversification", bias in
sampling ancestral nodes, failure to sample recent divergences or pushing them back in relative time (making
recent divergences older than expected)
"failure to detect recent bursts of speciation and instead inferring higher rates of evolution at earlier time
intervals"


