---
title: "cross-validation-pathd8"
output: html_document
---

We also demonstrate the usage of PATHd8 [@Britton2007] as a dating method alternative to BLADJ. PATHd8 requires a tree with initial branch lengths which we obtained using `datelife`'s branch length reconstruction algorithm, that searches for DNA sequence data from the Barcode of Life Data System [BOLD; @ratnasingham2007bold] to generate branch lengths. We were able to successfully generate a tree with BOLD branch lengths for all of the Fringillidae source chronograms. However, dating with PATHd8 using congruified calibrations, was only successful in
<!-- two studies when expanding calibrations to make them agree (studies 3 and 5), and from  -->
three cases (studies 3, 5, and 9, shown in Fig. \ref{fig:cvbold}).
<!-- What made it unsuccessful in the other cases? -->
From these, two trees have a different sampling than the original source chronogram, mainly because DNA BOLD  data for some species is absent from the database.
<!-- ??? Node ages or maximum ages?? -->
Maximum ages are quite different from source chronograms, but this might be explained also by the differences in sampling between source chronograms and BOLD trees.
More examples and code used to generate these trees were developed on an open repository that is available for consultation and reuse at <https://github.com/LunaSare/datelife_examples>.
