---
title             : "DateLife: Leveraging databases and analytical tools to reveal the dated Tree of Life"
shorttitle        : "Title"

author:
  - name          : "Luna L. Sánchez Reyes"
    affiliation   : "1,2"
    corresponding : yes    # Define only one corresponding author
    address       : ""
    email         : "sanchez.reyes.luna@gmail.com"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - Data curation
      - Investigation
      - Software
      - Visualization
      - Validation
      - Writing - Original Draft Preparation
      - Writing - Review & Editing
  - name          : "Emily Jane McTavish"
    affiliation   : "1"
    role:
      - Resources
      - Software
      - Writing - Review & Editing
  - name          : "Brian O'Meara"
    affiliation   : "2"
    role:
      - Conceptualization
      - Funding acquisition
      - Methodology
      - Resources
      - Software
      - Supervision
      - Writing - Review & Editing

affiliation:
  - id            : "1"
    institution   : "University of California, Merced"
  - id            : "2"
    institution   : "University of Tennessee, Knoxville"

authornote: |
  School of Natural Sciences, University of California, Merced, Science and Engineering Building 1.

  Department of Ecology and Evolutionary Biology, University of Tennessee, Knoxville, 425 Hesler Biology Building, Knoxville, TN 37996, USA.

abstract: |
  Time of evolutionary origin is fundamental for understanding biological processes.

  The combination of new analytical techniques, availability of more fossil and molecular
  data, and efforts to improve data sharing practices in biology has resulted in a steady accumulation
  of time of lineage divergence in public and open databases such as TreeBASE, Dryad, and Open Tree
  of Life for a large quantity and diversity of organisms in the last few decades.

  However, getting a tree with branch lengths proportional to time remains difficult for many biologists and the non-academic community, despite its importance for biological research, medicine, education, and science communication.

  Here we present `datelife`, a service implemented via an R package and a web site
  (<http://www.datelife.org/>) for efficient reuse, summary and reanalysis of expert, peer-reviewed, public data on time of lineage divergence.

  Main results:
    1. blah
    2. blah
    3. blah

  Results in a general context:
  All source and summary chronograms can be saved in formats that permit easy reuse and reanalysis. Summary and newly generated trees are potentially useful to evaluate evolutionary hypothesis in different areas of research in biology.
  How well this trees work for this purpose still needs to be tested.

  `datelife` will be useful to increase awereness on the existing variation in expert time of divergence data, and might foster exploration of the effect of alternative divergence time hypothesis on the results of analyses, nurturing a culture of more cautious interpretation of evolutionary results.

  <!-- https://tinyurl.com/ybremelq -->

keywords          : "keywords"
wordcount         : "X"

bibliography      : ["paper_references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
r_refs("paper_references.bib")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(50)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```



# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs" custom-style="Bibliography"></div>
\endgroup
