---
title: "dev_extract_calibrations"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{dev_extract_calibrations}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
devtools::load_all("../../datelifeplot")
devtools::load_all("../../datelife")
```


```{r}
load("../data/fringillidae_v0.6.2.rda")
```

`datelife_result_median`

```{r}
datelife_result <- fringillidae_v0.6.2$dres
median_matrix <- datelife_result_median_matrix(datelife_result)
nrow(median_matrix)

phy <- summary_matrix_to_phylo(median_matrix)
```

`summary_matrix_to_phylo`

```{r}
summ_matrix <- median_matrix
target_tree <- fringillidae_v0.6.2$dsumm$phylo_median # fringillidae_v0.6.2$dquery$phy
summ_matrix <- summ_matrix * 0.5 # bc it's total distance tip to tip

calibrations <- summarize_summary_matrix(summ_matrix)

```

`summarize_summary_matrix`

```{r}
ages <- tA <- tB <- c()
  # to compute the final length of the data frame do: ncol(xx)^2 - sum(1:(ncol(xx)-1))
  # calibrations <- matrix(nrow = ncol(xx)^2 - sum(1:(ncol(xx)-1)), ncol = 3)
  # identify if SDM matrix has some negative values; extract taxon names:
negs <- which(summ_matrix < 0)
neg_names <- rownames(summ_matrix)[ceiling(negs / nrow(summ_matrix))]
# extract unique ages from summ_matrix:
for (i in seq(ncol(summ_matrix))) {
    ages <- c(ages, summ_matrix[1:i, i])
    tA <- c(tA, rownames(summ_matrix)[1:i])
    tB <- c(tB, rep(colnames(summ_matrix)[i], i))
}
tA <- gsub(" ", "_", tA)
tB <- gsub(" ", "_", tB)

length(tA) == length(tB)
length(tA) == length(ages)
  # tA <- gsub(" ", "_", tA)
  # tB <- gsub(" ", "_", tB)
calibrations <- data.frame(Age = ages, taxonA = tA, taxonB = tB, stringsAsFactors = FALSE)
# check that final row number is correct:
nrow(calibrations) == ncol(summ_matrix)^2 - sum(1:(ncol(summ_matrix)-1))
# get rid of NaN and NAs
calibrations <- calibrations[!is.na(calibrations[, "Age"]), ]
# get rid of 0's
calibrations <- calibrations[calibrations[, "Age"] != 0, ]
# after cleaning we have less rows:
nrow(calibrations) # 29115
```
Order calibrations by taxon name and age:

```{r}
calibrations <- calibrations[order(calibrations$taxonA,
                                   calibrations$Age,
                                   calibrations$taxonB),]
rownames(calibrations) <- NULL
```

```{r}
calibrations <- calibrations[calibrations[, "Age"] > 0, ] # get rid of negative values too
# SDM summary matrix sometimes has negative values, bc ages are transformed to be approximated in a similar way as a linear regression
```

```{r}
target_tree_nodes <- sapply(seq(nrow(calibrations)), function(i) {
  phytools::findMRCA(
    tree = target_tree,
    tips = as.character(calibrations[i, c("taxonA", "taxonB")]),
    type = "node"
  )
})
length(target_tree_nodes) # 29115
target_tree_nodes <- target_tree_nodes - ape::Ntip(target_tree)
```

get the node age distribution

```{r}
all_nodes <- sort(unique(target_tree_nodes))
all_ages <- lapply(all_nodes, function(i) calibrations[target_tree_nodes == i, "Age"])
length(all_ages) # 229 nodes
all_ages[1]
sapply(all_ages, length)
```

```{r}
any(sapply(all_ages, is.null)) # if FALSE, all nodes have at least one calibration.
calibrations2 <- data.frame(MRCA = paste0("n", all_nodes), MinAge = sapply(all_ages, min), MaxAge = sapply(all_ages, max))
# calibrations2$MRCA is a factor so have to be made as.character to work with bladj
ls(calibrations2)
  if (all(all_nodes < ape::Ntip(target_tree))) {
    all_nodes_numbers <- all_nodes + ape::Ntip(target_tree)
    node_index <- "consecutive"
  } else {
    all_nodes_numbers <- all_nodes
    node_index <- "node_number"
  }
  target_tree$node.label <- NULL # make sure its null, so we can rename all nodes of interest to match our labels
  target_tree <- tree_add_nodelabels(tree = target_tree, node_index = node_index) 
  
tree_add_nodelabels(tree = target_tree, node_index = "consecutive")   
head(target_tree$node.label)
names(all_ages) <- paste0("n", all_nodes_numbers)

  node_ages_midpoint <- sapply(seq(nrow(calibrations2)),
                        function(i) sum(calibrations2[i, c("MinAge", "MaxAge")]) / 2)
  new_phy_midpoint <- make_bladj_tree(
    tree = target_tree, nodenames = as.character(names(all_ages)),
    nodeages = node_ages_midpoint
  )
```

Where do we use `summary_matrix_to_phylo`?

```{r}
all_summary_chronograms <- datelife::summary_matrix_to_phylo_all(median_matrix,
                                      fringillidae_v0.6.2$dquery,
                                      target_tree = fringillidae_v0.6.2$dsumm$phylo_sdm,
                                      total_distance = TRUE)

ls(all_summary_chronograms)
class(all_summary_chronograms)
all_summary_chronograms

midpoint_chronogram <- summary_matrix_to_phylo(median_matrix,
                                              target_tree = fringillidae_v0.6.2$dsumm$phylo_median,
                                              use = "midpoint")
```

Run the insides of `match_all_calibrations`

```{r}
match_all_calibrations
```
