---
title: "figure2"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{figure2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# library(datelifeMS1)
devtools::load_all()
frin_sample_dsumm$phylo_median
spp <- frin_sample_dsumm$phylo_median$tip.label[1:6]
spp_dq <- datelife::make_datelife_query(spp)
spp_dr <- datelife::get_datelife_result(spp_dq)
spp_summ <- datelife:::summary.datelifeResult(datelife_query = spp_dq, object = spp_dr)
spp_summ$phylo_all

mock_spp_names <- gsub(" ", "_", spp_summ$phylo_median$tip.label)
names(mock_spp_names) <- LETTERS[1:6]
mock_spp_names

mock_study_names <- names(spp_summ$phylo_all)
iis <- match(mock_study_names, unique(mock_study_names))
names(mock_study_names) <- paste("Study", iis)
names(mock_study_names)
ffs <- table(names(mock_study_names))

is_dupl <- names(mock_study_names) %in% names(ffs)[ffs > 1]

# Add "Chronogram X" to duplicated studies:

for (i in names(ffs)[ffs > 1]) {
  dds <- i == names(mock_study_names)
  chrono_names <- paste("- Chronogram", seq(ffs[[i]]))
  names(mock_study_names)[dds] <- paste(names(mock_study_names)[dds],chrono_names )
}
```

Rename source chronograms:

```{r}
phylo_all_renamed <- c()
for (phy in spp_summ$phylo_all){
  is_in_tree <- match(gsub(" ", "_", phy$tip.label), mock_spp_names)
  # print(is_in_tree)
  # print(phy$tip.label)
  # print(names(mock_spp_names)[is_in_tree])
  phy$tip.label <- names(mock_spp_names)[is_in_tree]
  phylo_all_renamed <- c(phylo_all_renamed, list(phy))
}
class(phylo_all_renamed) <- "multiPhylo"
names(phylo_all_renamed) <- names(mock_study_names)
```

Plotting one chronogram as test:
```{r}
time_depth <- 45
chronogram <- phylo_all_renamed[[1]]
chronogram$root.edge <- time_depth - max(ape::branching.times(chronogram))

ape::plot.phylo(chronogram,
                cex = 1, #edge.width = 2,
                label.offset = 0.5,
                x.lim = c(0, time_depth),
                root.edge = TRUE,
                plot = TRUE, edge.width = 2)
ape::axisPhylo(line = 1)

datelifeplot::plot_phylo(chronogram,
                         title = names(phylo_all_renamed)[1],
                         plot_type = "ape",
                         time_depth = 45,
                         write = "pdf",
                         file_name = "test.pdf",
                         cex_tiplabels = 2,
                         cex_axislabel = 1.5,
                         cex_title = 2,
                         pos_title = 2.2,
                         pos_axis = 2)
```


Plotting ALL source chronograms


```{r}
# as png, but resolution is not good and it is hard to fix within plot_phylo
# png plots are in vignettes/phylo_all/png
datelifeplot::plot_phylo_all(trees = phylo_all_renamed,
                             write = "png")

# as pdf:
max(ape::branching.times(phylo_all_renamed[[9]]))  # 44.29586

devtools::load_all("../datelifeplot")
datelifeplot::plot_phylo_all(chronograms = phylo_all_renamed,
                             write = "pdf",
                             plot_type = "phyloch",
                             max_depth = 45,
                             edge.width = 2,
                             cex_tiplabels = 2,
                             cex_axislabel = 1.5,
                             cex_axis = 2,
                             cex_title = 2,
                             pos_title = 2.2,
                             pos_axis = 2,
                             units = NULL)
```


combine with magick:

```{r}
for (i in seq(phylo_all_renamed)) {
  ii <- magick::image_read(path = paste0("phylo_all/phylo_all_", i, ".pdf"))
  assign(x = paste0("phy", i), value = ii)
}
img <- c(phy1, phy2, phy3, phy4, phy5, phy6, phy7, phy8, phy9)
img <- magick::image_scale(img, "300x")
magick::image_info(img)

pdf("stacked.pdf")
magick::image_append(magick::image_scale(img, "200x"))
dev.off()
```
