---
title: "figure-cross-validation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{figure-cross-validation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(datelifeMS1)
devtools::load_all("../../datelifeplot")
devtools::load_all("../../datelife")
writing_dir <- "../figures/figure-cross-validation/"

# Based on function use_othercals3 from https://github.com/LunaSare/datelife_examples/blob/master/R/functions_data.R#L36
use_other_calibrations <- function(trees, other_calibrations, ...){
    res <- lapply(seq(trees), function(i){
      phy <- trees[[i]]
      phy$edge.length <- NULL
      print(i)
        xx <- suppressMessages(suppressWarnings(datelife::use_calibrations_bladj(phy,
            calibrations = other_calibrations[[i]], ...)))
        return(xx)
    })
    class(res) <- "multiPhylo"
    names(res) <- names(trees)
    res
}
```

## Cross validation of Fringillidae source chronograms.

We are using the object `frin_dsumm` and getting all source chronograms, and reordering the chronogram list alphabetically:

```{r}
phylo_all <- frin_dsumm$phylo_all
alphabetic_order <- order(names(phylo_all))
phylo_all <- phylo_all[alphabetic_order]
```

We will rename source chronograms to have a shorter study name:

```{r}
names(phylo_all) <- c("Barker et al. 2013",  # 1
                      "Barker et al. 2015 - chronogram 1",  # 2
                      "Barker et al. 2015 - chronogram 2",  # 3
                      "Burns et al. 2015",  # 4
                      "Claramunt et al. 2015",  # 5
                      "Gibb et al. 2015", # 6
                      "Hedges et al. 2015 - chronogram 1",  # 7
                      "Hedges et al. 2015 - chronogram 2",  # 8
                      "Hooper et al. 2017",  # 9
                      "Jetz et al. 2012 - chronogram 1",  # 10
                      "Jetz et al. 2012 - chronogram 2",  # 11
                      "Kimball et al. 2019 - chronogram 1", # 12
                      "Kimball et al. 2019 - chronogram 2", # 13
                      "Oliveros et al. 2019", # 14
                      "Price et al. 2014 - chronogram 1", # 15
                      "Price et al. 2014 - chronogram 2", # 16
                      "Roquet et al. 2014 - chronogram 1", # 17
                      "Roquet et al. 2014 - chronogram 2", # 18 
                      "Uyeda et al 2017") # 19
```

Next, get calibrations for all other chronograms:
```{r}
# Function based on https://github.com/LunaSare/datelife_examples/blob/master/R/functions_data.R#L3
# get calibrations form all other chronograms not belonging to the same study
congruify_other_calibrations <- function(phylo_all){
    # dd <- duplicated(names(phyloall))
    res <- lapply(seq(phylo_all), function(i){
        cat(i, " -- ", names(phylo_all)[i], "\n")
        dd <- names(phylo_all) %in% names(phylo_all)[i]
        datelife::congruify_calibrations(phy = phylo_all[dd][[1]],
                                         chronograms = phylo_all[!dd])
    })
    names(res) <- names(phylo_all)
    res
}
```

```{r}
frin_other_calibs <- congruify_other_calibrations(phylo_all)
class(frin_other_calibs)
length(frin_other_calibs)
names(frin_other_calibs) <- names(phylo_all)
frin_other_calibs[[1]]
```

Date the topology based on other calibrations:

```{r}
# Function to date source chronograms with data from other chronograms
cross_date <- function(frin_other_calibs, index) {
  cat(index, " -- ", names(frin_other_calibs)[index], "\n")
  
  calibrations <- frin_other_calibs[[index]]
  
  if (length(calibrations) == 1) {
    message("... Source chronogram has no calibrations.")
    return(NA)
  }
  
  mm <- calibrations$matched_calibrations
  mm <- mm[mm$congruent,]
  mm <- mm[!is.na(mm$mrca_node_number),]
  calibrations$matched_calibrations <- mm
  res <- use_calibrations_bladj.matchedCalibrations(                     
                         calibrations = calibrations, 
                         type = "mean")
  res
}

validated_trees <- lapply(seq(frin_other_calibs), function(i) 
  cross_date(frin_other_calibs, index = i))

names(validated_trees) <- names(frin_other_calibs)

usethis::use_data(validated_trees)

```

Plots

```{r}
index = 1
ls(validated_trees[[index]])
plot_max_time <- 45

plot_all <- function(writing_dir, 
                     index = 1, 
                     height = 11*72, 
                     phylo_all, 
                     validated_trees, 
                     plot_max_time = 45,
                     cex_tiplabels = 1,
                     mai4 = 1) {
    #
  if (length(validated_trees[[index]]) == 1) {
    return(NA)
  }
  grDevices::png(filename = paste0(writing_dir, "cross_validation_", index, ".png"),
      height = height,
      width = 5*72,
      bg = "transparent")
  plot_chronogram(chronogram = phylo_all[[index]],
                         title = "",
                         time_depth = plot_max_time,
                         time_axis = FALSE,
                         axis_label = "",
                         edge.width = 3,
                         cex_tiplabels = cex_tiplabels,
                         mai4 = mai4)

  plot_chronogram(chronogram = validated_trees[[index]],
                         title = names(validated_trees)[index],
                         time_depth = plot_max_time,
                         time_axis = TRUE,
                         axis_label = "",
                         edge.width = 3,
                         edge.color = "#77889980",
                         cex_tiplabels = cex_tiplabels,
                         tip.color = "#77889900",
                         cex_axislabel = 1,
                         cex_axis = 1,
                         cex_title = 1.5,
                         pos_title = 2,
                         mai4 = mai4)
dev.off()
}

nice_height <- c(792, 792, 792, 792, NA, 300, 792, 792, 792, 792)
nice_cex <- c(1, 0.5, 0.5, 1, NA, 1, 0.2, 0.2, 0.8, 0.5)
i = 10
for (i in 1:8) {
    plot_all(writing_dir = writing_dir,
             index = i, 
             height = nice_height[i],
             phylo_all = phylo_all,
             validated_trees = validated_trees,
             cex_tiplabels = nice_cex[i],
             mai4 = 2.37)
}
```
