---
title: "taxa"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{taxa}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(datelife)
library(magrittr)
opentree_chronograms$version
opentree_chronograms$trees[[1]]$ott_ids
taxon_ott_ids <- unique(as.numeric(unlist(sapply(opentree_chronograms$trees, "[", "ott_ids"))))
which(is.na(taxon_ott_ids))
taxon_ott_ids <- taxon_ott_ids[!is.na(taxon_ott_ids)]
write(paste0(taxon_ott_ids, " "), file = "../data-raw/chronogram_taxon_ott_ids.txt")
```

```{r}
class(taxon_ott_ids)
length(taxon_ott_ids)
```

There are `r length(taxon_ott_ids)` taxon OTT ids in the OpenTree chronograms DateLife database version `r opentree_chronograms$version`.

What is the taxonomic distribution of these OTT ids?

```{r}
xx <- rotl::taxonomy_taxon_info(taxon_ott_ids[1], include_lineage = TRUE) 
sapply(xx$`461645`$lineage, "[", "name") %>% 
  unlist() %>% 
  unname() -> taxonomy
class(taxonomy)
taxonomy
```

```{r}
tip_labels <- unique(unlist(sapply(opentree_chronograms$trees, "[", "tip.label")))
anyDuplicated(tip_labels)
ott_ids <- unique(unlist(sapply(opentree_chronograms$trees, "[", "ott_ids")))
length(ott_ids)
data.frame(opentree_chronograms$trees[[1]]$tip.label,
opentree_chronograms$trees[[1]]$ott_ids)
length(opentree_chronograms$trees[[1]]$tip.label) == length(opentree_chronograms$trees[[1]]$ott_ids)

equal_length <- sapply(seq(opentree_chronograms$trees), function(i) {
  length(opentree_chronograms$trees[[i]]$tip.label) == length(opentree_chronograms$trees[[i]]$ott_ids)
})

length(opentree_chronograms$trees[[100]]$tip.label) == length(opentree_chronograms$trees[[100]]$ott_ids)
```

```{r}
tnrs100 <- rotl::tnrs_match_names(opentree_chronograms$trees[[100]]$tip.label)
tnrs100
```

```{r}
tip_labels_tnrs <- rotl::tnrs_match_names(tip_labels)
tip_labels_tnrs[1:10,]
length(tip_labels)
length(tip_labels) == nrow(tip_labels_tnrs)
sum(is.na(tip_labels_tnrs$ott_id))
# 99474 unique tip labels
# 979 do not have OTT id
```



