# datelifeplot::plot_node_ages(my_chronogram,
#                title = "Median Summary Chronogram",
#                plot_type = "phyloch",
#                time_depth = 45,
#                calibration_summary = calib_summ,
#                pch = 19,
#                color_pch = color_studies,
#                cex_pch = 1,
#                lwd_bars = 10,
#                cex_legend = 0.7,
#                x_legend = 0 ,
#                y_legend = 270,
#                mai1 = 1,
#                mai2 = 0,
#                mai3 = 0.5,
#                mai4 = 3.73,
#                omi1 = 2,
#                omi2 = 1,
#                omi3 = 0.5,
#                omi4 = 0,
#                edge.width = 2,
#                cex_tiplabels = 0.5,
#                cex_axislabel = 1,
#                cex_axis = 1,
#                cex_title = 2,
#                pos_title = -1,
#                pos_axis = 2
#                )
